version: "3.5"

networks:
  traefiknet:
    name: traefiknet

services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: utils-homer
    volumes:
      - homer:/www/assets
    ports:
      - 82:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`homer.home.arpa`)"
      - "traefik.http.routers.homer.entrypoints=web"
      - "traefik.docker.network=traifiknet"

  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration feature
    ports:
      - 5005:5005
    environment:
      - PASSWORD=flame_password
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flame.rule=Host(`flame.home.arpa`)"
      - "traefik.http.routers.flame.entrypoints=web"
      - "traefik.docker.network=traifiknet"


volumes:
  homer:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.55.21,nfsvers=4,hard"
      device: ":/volume1/docker-data/homer"

  flame:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.55.21,nfsvers=4,hard"
      device: ":/volume1/docker-data/flame"