services:
  dns01:
    container_name: dns02
    hostname: dns02
    image: technitium/dns-server:latest
    # used host network mode as it is running DHCP as well as DNS
    network_mode: "host"
    environment:
      - DNS_SERVER_DOMAIN=home.arpa #The primary domain name used by this DNS Server to identify itself.
    volumes:
      - /home/manderse/docker/dns02:/etc/dns
    restart: unless-stopped