version: "3,5"

networks:
  traefiknet:
    name: traefiknet

services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: dnloads-sonarr
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.home.arpa`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.docker.network=traifiknet"
    volumes:
      - dnloads/sonarr/config:/config
      - /mnt/fs02-media:/mnt/fs02-media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ="America/Los_Angeles"
      - PUID=1000
      - PGID=1000
    ports:
      - '8989:8989'
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: dnloads-radarr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.home.arpa`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.docker.network=traifiknet"
    volumes:
      - /docker-data/dnloads/radarr/config:/config
      - /mnt/fs02-media:/mnt/fs02-media
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - traefiknet


  jackett:
    container_name: dnloads-jackett
    image: ghcr.io/linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - '9117:9117'
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker-data/dnloads/jackett/config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.home.arpa`)"
      - "traefik.http.routers.jackett.entrypoints=web"
      - "traefik.docker.network=traifiknet"

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
#    image: lscr.io/linuxserver/lidarr:1.1.1-nightly
    container_name: dnloads-lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /docker-data/dnloads/lidarr/config:/config
      - /mnt/fs02-media:/fs02-media #optional
      - /mnt/leda_complete/tor-music-archive:/tor-music-archive #optional
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.home.arpa`)"
      - "traefik.http.routers.lidarr.entrypoints=web"
      - "traefik.docker.network=traifiknet"
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: dnloads-prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /docker-data/dnloads/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.home.arpa`)"
      - "traefik.http.routers.prowlarr.entrypoints=web"
      - "traefik.docker.network=traifiknet"

  overseerr:
    image: sctx/overseerr:latest
    container_name: dnloads-overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /docker-data/dnloads/overseerr:/app/config
    restart: unless-stopped
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.home.arpa`)"
      - "traefik.http.routers.overseerr.entrypoints=web"
      - "traefik.docker.network=traifiknet"


volumes:
  dnloads:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.55.21,nfsvers=4,hard"
      device: ":/volume1/docker-data/dnloads"