---
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/docker/emby:/config
      - fs02-media:/data/fs02-media
      - tnas01-media:/data/tnas01-media
    ports:
      - 8096:8096
      - 8920:8920 #optional
    
    restart: unless-stopped
    networks:
      - proxy    
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.ar-emby.rule=Host(`ar-emby.crzynet.com`)"
      - "traefik.http.routers.ar-emby.tls=true"
      - "traefik.http.services.ar-emby.loadbalancer.server.port=8096"        

volumes:
  fs02-media:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.55.22,nfsvers=4,hard"
      device: ":/volume1/media"      
  tnas01-media:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.55.24,nfsvers=4,hard"
      device: ":/mnt/Raid01/media"