services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    ports:
      - 6052:6052
    #network_mode: "host"
    environment:
      - TZ=america/los_angeles
      - ESPHOME_DASHBOARD_USE_PING=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - esphome:/config:rw
    restart: unless-stopped
    privileged: true

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.esphome.rule=Host(`esphome.crzynet.com`)"
      - "traefik.http.routers.esphome.tls=true"
      - "traefik.http.services.esphome.loadbalancer.server.port=6052" 

    networks:
      - proxy

networks:
  proxy:
    external: true
volumes:
  esphome:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.55.21,nfsvers=4,hard"
      device: ":/volume1/docker-data/iotutils/esphome"      