version: "3.5"
# Docker Compose for Portainer Agent

networks:
  traefiknet:
    name: traefiknet
services:
  portainer-agent:
    image: portainer/agent:latest
    user: 1000:1000
    container_name: portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    restart: unless-stopped
    networks:
      - traefiknet