services:
  homeassistant: 
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/manderse/docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus:/run/dbus:ro
    restart: always
    network_mode: host
    labels:
      # Enable this container to be mapped by traefik
      # For more information, see: https://docs.traefik.io/providers/docker/#exposedbydefault
      - "traefik.enable=true"
      # Define the network that should be used
      - "traefik.docker.network=proxy"
      # URL to reach this container
      - "traefik.http.routers.home-assistant.rule=Host(`hass.crzynet.com`)"
      # Activation of TLS
      - "traefik.http.routers.home-assistant.tls=true"
      # If port is different than 80, use the following service:
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"


