version: "3,5"

networks:
  traefiknet:
    name: traefiknet

services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

#  sonarr:
#    image: ghcr.io/linuxserver/sonarr:latest
#    container_name: dnloads-sonarr
#    networks:
#      - traefiknet
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.sonarr.rule=Host(`sonarr.home.arpa`)"
#      - "traefik.http.routers.sonarr.entrypoints=web"
#      - "traefik.docker.network=traifiknet"
#      - flame.type=application # "app" works too
#      - flame.name=Sonarr
#      - flame.url=http://sonarr.home.arpa
      #- flame.icon=icon-name # optional, default is "docker"
#    volumes:
#      - /local-data/dnloads/sonarr/config:/config
#      - fs02-media:/mnt/fs02-media
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#      - TZ="America/Los_Angeles"
#      - PUID=1000
#      - PGID=1000
#    ports:
#      - '8989:8989'
#    restart: unless-stopped

#  radarr:
#    image: ghcr.io/linuxserver/radarr:latest
#    container_name: dnloads-radarr
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.radarr.rule=Host(`radarr.home.arpa`)"
#      - "traefik.http.routers.radarr.entrypoints=web"
#      - "traefik.docker.network=traifiknet"
#    volumes:
#      - /local-data/dnloads/radarr/config:/config
#      - fs02-media:/mnt/fs02-media
#      - tnas01-media:/mnt/tnas01-media
#    environment:
#      - TZ=America/Los_Angeles
#      - PUID=1000
#      - PGID=1000
#    ports:
#      - 7878:7878
#    restart: unless-stopped
#    networks:
#      - traefiknet

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
#    image: lscr.io/linuxserver/lidarr:1.1.1-nightly
    container_name: dnloads-lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /local-data/dnloads/lidarr/config:/config
      - /mnt/fs02-media:/fs02-media #optional
      - /mnt/luna_complete/tor-music-archive:/tor-music-archive #optional
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`lidarr.home.arpa`)"
      - "traefik.http.routers.lidarr.entrypoints=web"
      - "traefik.docker.network=traifiknet"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: dnloads-prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /local-data/dnloads/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.home.arpa`)"
      - "traefik.http.routers.prowlarr.entrypoints=web"
      - "traefik.docker.network=traifiknet"

  overseerr:
    image: sctx/overseerr:latest
    container_name: dnloads-overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /local-data/dnloads/overseerr:/app/config
    restart: unless-stopped
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.home.arpa`)"
      - "traefik.http.routers.overseerr.entrypoints=web"
      - "traefik.docker.network=traifiknet"

  ombi:
    image: ghcr.io/linuxserver/ombi:latest
    container_name: dnloads-ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
#      - BASE_URL=/ombi #optional
#      - VIRTUAL_HOST=dc-o.loginet.com
    volumes:
      - /local-data/dnloads/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped


#  syncthing:
#    image: syncthing/syncthing
#    container_name: dnloads-syncthing
#    hostname: archive-syncthing
#    environment:
#      - PUID=1000
#      - PGID=1000
#    volumes:
#      - /mnt/fs02-media/working:/mnt/fs02-media-working
#      - syncthing:/var/syncthing
#    ports:
#      - 8384:8384
#      - 22000:22000/tcp
#      - 22000:22000/udp
#    restart: unless-stopped
#    networks:
#      - traefiknet
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.syncthing.rule=Host(`syncthing.home.arpa`)"
#      - "traefik.http.routers.syncthing.entrypoints=web"
#      - "traefik.docker.network=traifiknet"


  headphones:
    image: lscr.io/linuxserver/headphones:latest
    container_name: headphones
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /local-data/dnloads/headphones/config:/config
      - /local-data/dnloads/headphones/downloads:/downloads
      - /mnt/fs02-media/Music_New:/music
    ports:
      - 8181:8181
    restart: unless-stopped

  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /local-data/dnloads/beets/config:/config
      - /mnt/fs02-media/music:/music
      - /mnt/fs02-media/Music_New:/downloads
    ports:
      - 8337:8337
    restart: unless-stopped

volumes:
  
  fs02-media:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.55.22,vers=4,soft,nolock,rw"
      device: ":/volume1/media"
  
  tnas01-media:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.55.24,vers=4,soft,nolock,rw"
      device: ":/mnt/Raid01/media"


  syncthing:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.55.21,vers=4.1,hard"
      device: ":/volume1/docker-data/dnloads/syncthing/config"      
      