services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3002:3000
    volumes:
      - /home/mander/docker/dnloads/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      - HOMEPAGE_VAR_SONARR_API=${HOMEPAGE_VAR_SONARR_API}
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS} 


  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: dc-bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/mander/docker/dnloads/bazarr/config:/config
      - /mnt/seanas01_media:/mnt/seanas01_media
      - /mnt/seanas02_media:/mnt/seanas02_media
    ports:
      - 6767:6767
    labels:
      - "dockflare.enable=true"
      - "dockflare.hostname=dc-bazarr.crzynet.com"
      - "dockflare.service=http://dc-bazarr:6767"
      - "dockflare.access.policy=authenticate"
      - "dockflare.access.group=dnload-admins"

      - dockernotifier.notifiers=service-tracker-dashboard
      - dockernotifier.std.internalurl=https://dc-bazarr.crzynet.com/
      - dockernotifier.std.internal.health=true
      - dockernotifier.std.externalurl=http://192.168.20.91:6767
      - dockernotifier.std.external.health=true
      - dockernotifier.std.group=dnloads
      
    restart: unless-stopped
    networks:
      - proxy  
      - cloudflare-net

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: dc-sonarr
    volumes:
      - /home/mander/docker/dnloads/sonarr/config:/config
      - /mnt/seanas01_media:/mnt/seanas01_media
      - /mnt/seanas02_media:/mnt/seanas02_media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ="America/Los_Angeles"
      - PUID=1000
      - PGID=1000
    ports:
      - '8989:8989'
    labels:
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=dc-sonarr.crzynet.com"
      - "cloudflare.tunnel.service=http://dc-sonarr:8989"
      - "cloudflare.tunnel.access.policy=authenticate"
      - "cloudflare.tunnel.access.name=dc-sonarr"
      - dockernotifier.notifiers=service-tracker-dashboard
      - dockernotifier.std.internalurl=http://192.168.20.91:8989
      - dockernotifier.std.internal.health=true
      - dockernotifier.std.externalurl=https://dc-sonarr.crzynet.com/
      - dockernotifier.std.external.health=true
      - dockernotifier.std.group=dnloads

    restart: unless-stopped
    networks:
      - proxy      

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: dc-radarr
    volumes:
      - /home/mander/docker/dnloads/radarr/config:/config
      - /mnt/seanas01_media:/mnt/seanas01_media
      - /mnt/seanas02_media:/mnt/seanas02_media
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    labels:
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=dc-radarr.crzynet.com"
      - "cloudflare.tunnel.service=http://dc-radarr:7878"
      - "cloudflare.tunnel.access.policy=authenticate"
      - "cloudflare.tunnel.access.name=dc-radarr"      
      - dockernotifier.notifiers=service-tracker-dashboard
      - dockernotifier.std.internalurl=http://192.168.20.91:7878
      - dockernotifier.std.internal.health=true
      - dockernotifier.std.externalurl=https://dc-radarr.crzynet.com/
      - dockernotifier.std.external.health=true
      - dockernotifier.std.group=dnloads      
    restart: unless-stopped
    networks:
      - proxy      


  ombi:
    image: ghcr.io/linuxserver/ombi:latest
    container_name: dc-ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/mander/docker/dnloads/ombi:/config
    ports:
      - 3579:3579
    labels:
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=dc-ombi.crzynet.com"
      - "cloudflare.tunnel.service=http://dc-ombi:3579"
      - "cloudflare.tunnel.access.policy=bypass"
      - dockernotifier.notifiers=service-tracker-dashboard
      - dockernotifier.std.internalurl=http://192.168.20.91:3579
      - dockernotifier.std.internal.health=true
      - dockernotifier.std.externalurl=https://dc-ombi.crzynet.com/
      - dockernotifier.std.external.health=true
      - dockernotifier.std.group=dnloads      
    restart: unless-stopped
    networks:
      - proxy      


  syncthing:
    image: syncthing/syncthing
    container_name: dc-syncthing
    hostname: dc-syncthing
    environment: 
      - PUID=1000 
      - PGID=1000 
    volumes:
      - /mnt/seanas02_media/Working:/mnt/seanas02-media-working
      - /home/mander/docker/dnloads/syncthing/config:/var/syncthing
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    labels:
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=dc-syncthing.crzynet.com"
      - "cloudflare.tunnel.service=http://dc-syncthing:7878"
      - "cloudflare.tunnel.access.policy=authenticate"
      - "cloudflare.tunnel.access.name=dc-syncthing"      
      - dockernotifier.notifiers=service-tracker-dashboard
      - dockernotifier.std.internalurl=http://192.168.20.91:8384
      - dockernotifier.std.internal.health=true
      - dockernotifier.std.externalurl=https://dc-syncthing.crzynet.com/
      - dockernotifier.std.external.health=true
      - dockernotifier.std.group=dnloads            
    restart: unless-stopped
    networks:
      - proxy      

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: dc-prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/mander/docker/dnloads/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=dc-prowlarr.crzynet.com"
      - "cloudflare.tunnel.service=http://dc-prowlarr:9696"
      - "cloudflare.tunnel.access.policy=authenticate"
      - "cloudflare.tunnel.access.name=dc-prowlarr"
      - dockernotifier.notifiers=service-tracker-dashboard
      - dockernotifier.std.internalurl=http://192.168.20.91:9696
      - dockernotifier.std.internal.health=true
      - dockernotifier.std.externalurl=https://dc-prowlarr.crzynet.com/
      - dockernotifier.std.external.health=true
      - dockernotifier.std.group=dnloads      
    networks:
      - proxy      

  overseerr:
    image: sctx/overseerr:latest
    container_name: dc-overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
      - PORT=5055 #optional
    ports:
      - 5055:5055
    labels:
      - "cloudflare.tunnel.enable=true"
      - "cloudflare.tunnel.hostname=dc-os.crzynet.com"
      - "cloudflare.tunnel.service=http://dc-overseerr:5055"
      - "cloudflare.tunnel.access.policy=bypass"
      - dockernotifier.notifiers=service-tracker-dashboard
      - dockernotifier.std.internalurl=http://192.168.20.91:5055
      - dockernotifier.std.internal.health=true
      - dockernotifier.std.externalurl=https://dc-os.crzynet.com/
      - dockernotifier.std.external.health=true
      - dockernotifier.std.group=dnloads       
    volumes:
      - /home/mander/docker/dnloads/overseerr:/app/config
    restart: unless-stopped
    networks:
      - proxy     

networks:
  proxy:
    external: true
  cloudflare-net:
    external: true    