services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_REMOTE_AGENT=192.168.20.210:7007
    ports:
      - 8080:8080
    labels:
      - "dockflare.enable=true"
      - "dockflare.hostname=dc-dozzle.crzynet.com"
      - "dockflare.service=http://dozzle:8080"
      - "dockflare.access.policy=authenticate"
      - "dockflare.access.group=dnload-admins"          
      
      - dockernotifier.notifiers=service-tracker-dashboard
      - dockernotifier.std.internalurl=https://dc-dozzle.crzynet.com/
      - dockernotifier.std.internal.health=true
      - dockernotifier.std.externalurl=http://192.168.20.91:8080
      - dockernotifier.std.external.health=true
      - dockernotifier.std.group=Utilities
      - dockernotifier.std.sort.priority=4
    networks:
      - cloudflare-net  

# START DOCKFLARE BLOCK
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:v0.4.1
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CONTAINERS=1
      - EVENTS=1
      - NETWORKS=1
      - IMAGES=1
      - POST=1
      - PING=1
      - INFO=1
      - EXEC=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dockflare-internal

  dockflare-init:
    image: alpine:3.20
    command: ["sh", "-c", "chown -R 65532:65532 /app/data"]
    volumes:
      - /var/docker/dockflare/data:/app/data
    networks:
      - dockflare-internal
    restart: "no"

  dockflare:
    image: alplat/dockflare:stable
    container_name: dockflare
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dockflare.rule=Host(`dc-dockflare.crzynet.com`)"
      - "traefik.http.routers.dockflare.tls=true"
      - "traefik.http.services.dockflare.loadbalancer.server.port=5000" 
    
      - dockernotifier.notifiers=service-tracker-dashboard
      - dockernotifier.std.internalurl=https://ar-dockflare.crzynet.com/
      - dockernotifier.std.internal.health=true
      - dockernotifier.std.group=docker-utils
      - dockernotifier.std.sort.priority=1

    ports:
      - "5000:5000"
    volumes:
      - /var/docker/dockflare/data:/app/data
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_DB_INDEX=0  # Optional: specify Redis database index (0-15) for isolation from other containers
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
    depends_on:
      docker-socket-proxy:
        condition: service_started
      dockflare-init:
        condition: service_completed_successfully
      redis:
        condition: service_started
    networks:
      - cloudflare-net
      - dockflare-internal
      - proxy

  redis:
    image: redis:7-alpine
    container_name: dockflare-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - /var/docker/dockflare/redis:/data
    networks:
      - dockflare-internal

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /dev:/host/dev:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'   

  tsbridge:
    image: ghcr.io/jtdowney/tsbridge:latest
    command: ["--provider", "docker"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Required for label discovery
      - tsbridge-state:/var/lib/tsbridge
    environment:
      - TS_OAUTH_CLIENT_ID=${TS_OAUTH_CLIENT_ID}
      - TS_OAUTH_CLIENT_SECRET=${TS_OAUTH_CLIENT_SECRET}
    labels:
      - "tsbridge.tailscale.oauth_client_id_env=TS_OAUTH_CLIENT_ID"
      - "tsbridge.tailscale.oauth_client_secret_env=TS_OAUTH_CLIENT_SECRET"
      - "tsbridge.tailscale.state_dir=/var/lib/tsbridge"
      - "tsbridge.tailscale.default_tags=tag:server" # Must match or be owned by your OAuth client's tag

    networks:
      - tailscale
      - proxy
      - cloudflare-net         

networks:
  cloudflare-net:
    name: cloudflare-net
    external: true
  proxy:
    external: true
  dockflare-internal:
    name: dockflare-internal  
  tailscale:
    name: tailscale    

  volumes:
  tsbridge-state:


