services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"

    labels:
      - "dockflare.enable=true"
      - "dockflare.hostname=dc-prom.crzynet.com"
      - "dockflare.service=http://prometheus:9090"
      - "dockflare.access.policy=authenticate"
      - "dockflare.access.group=dnload-admins"   
      - dockernotifier.enable=true
      - dockernotifier.notifiers=service-tracker-dashboard
      - dockernotifier.std.internalurl=https://dc-prom.crzynet.com/
      - dockernotifier.std.externalurl=https://dc-prom.crzynet.com/
      - dockernotifier.std.internal.health=true  
      - dockernotifier.std.group=monitoring    
    volumes:
      - /var.docker/prometheus/config.yml:/etc/prometheus/prometheus.yml
      - /var/docker/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true    

