services:
  tracker:
    image: crzykidd/service-tracker-dashboard:latest
    container_name: service-tracker-dash
    ports:
      - "8815:8815"
    volumes:
      - /var/docker/std:/config
    labels:
      - "dockflare.enable=true"
      - "dockflare.hostname=dc.crzynet.com"
      - "dockflare.service=http://service-tracker-dash:8815"
      - "dockflare.access.policy=authenticate"
      - "dockflare.access.group=dnload-admins

      - dockernotifier.notifiers=service-tracker-dashboard
      - dockernotifier.std.internalurl=http://192.168.20.91:8815
      - dockernotifier.std.internal.health=true
      - dockernotifier.std.externalurl=https://dc.crzynet.com
      - dockernotifier.std.external.health=true
      - dockernotifier.std.group=Utilities

    networks:
       cloudflare-net:
      
networks:
  proxy:
    external: true
  cloudflare-net:
    external: true